### ISSUE TITLE
构建表格的过程中出现行丢失的情况

### ISSUE THREAD

**Issue by LeifYaoYuXiang** [wuxue107/bookjs-eazy#8]
您好，
我在尝试使用Flask作为后端，前端通过[bookjs-eazy](https://github.com/wuxue107/bookjs-eazy)进行渲染生成PDF的过程中，出现了这样的问题：
当一个表格的长度超过规定的页面长度的时候，表格会自动分页，但是分页的最后一行会丢失（例如，一页可以展示10行表格，我有12行表格需要渲染），那么分页之后第11行会丢失

**Comment by wuxue107** [comment]
是多少版本， 最好可以在这里编辑一个出现问题的样例，保存或复制链接到这里，以方便排查

**Comment by LeifYaoYuXiang** [comment]
感谢您的回复。
我目前用的是最新的版本（1.17.5）
在实现的过程中，我利用了Flask的Jinja2进行渲染：
1. 我首先定义了表和表头：
```
<table class="nop-simple-table-2" data-op-type="table">
        <thead class="nop-fill-box" style="background: lightgrey">
        <tr>
            <td width="100">姓名</td>
            <td width="100">类别</td>
        </tr>
        </thead>
</table>
```
2. 其次，我定义了一个macro，规范表格每一行的格式：
```
{% macro row(user_name, user_type)%}
<tr style="background: antiquewhite">
          <td data-split-repeat="true">{{ user_name }}</td>
          <td data-split-repeat="true">{{ user_type }}</td>
</tr>
{% endmacro %}
```
3. 在此基础上，我通过for循环实现了加载每一行：
```
<tbody>
{% for each_user_row in rows %}
{{ row(each_user_row.user_name, each_user_row.user_type) }}
{% endfor %}
</tbody>
```
上面的代码中，`rows`为后端传过来的数据（数组字典），`row`为上文macro定义的行。

全部代码如下：
```
<table class="nop-simple-table-2" data-op-type="table">
        <thead class="nop-fill-box" style="background: lightgrey">
        <tr>
            <td width="100">姓名</td>
            <td width="100">类别</td>
        </tr>
        </thead>
        <tbody>
        {% for each_user_row in rows %}
            {{ row (each_user_row.user_name, each_user_row.user_type) }}
        {% endfor %}
        </tbody>
</table>
```
现在问题如下：当我后端传入12行的时候，如果前端每一页PDF只可以展示10行，那么可以分成两页，第一页展示1-10的内容；第二页展示第12行的内容；其中第11行的内容缺失。
我在尝试解决上述问题的过程中，利用浏览器进行过“检查”，在“Elements”选项卡中，确认没有第11行对应的<tr>标签，而前1-10行的<tr>标签可以正常展示。

**Comment by wuxue107** [comment]
大致确定了，问题的原因。是因为列中列中所有的列都标记了data-split-repeat="true" , data-split-repeat="true" 主要用于归类中合并行。至少保留一列不标记data-split-repeat="true" ，如：   [表格示例](https://bookjs.zhouwuxue.com/static/book-tpl/editor.html?code=J2QR8NGC) 中的“生物类别”、“子类别” 列。 后面我看一下，是否在运行期给予检测并提示，或文档中给予说明

**Comment by LeifYaoYuXiang** [comment]
感谢您的回复，经确认已解决，万分感谢！
